USE foriou;

-- GENERATE PRODUCTS
INSERT INTO products(name, vendor, unit_price, discounted_price, rating, image_url, description, inventory_count, created_at, updated_at)
VALUES
  ('Men\'s Shirt Black', 'Champion', 700, 700, 0.9, 'https://m.media-amazon.com/images/I/81PqX7YyLBL._AC_SY550_.jpg', "Product details Fabric type 100% Cotton Care instructionsMachine Wash OriginImported Neck styleCrew Neck About this item THE FIT - Standard-fit men's T-shirt for a classic look. THE FEEL - Crafted from a soft, 5.5 oz. cotton or cotton blend. THE LOOK - Classic short-sleeve style with ribbed crew neckline and soft back neck tape. SPOT THE C - Iconic C logo at the chest and left sleeve are recognizable on and off the field. Note: C logo patch color may vary from image.", 10, NOW(), NOW()),
  ('Men\'s Shirt White', 'Champion', 700, 700, 1, 'https://m.media-amazon.com/images/I/51dPz+dQTZL._AC_SX522_.jpg', "Product details Fabric type 100% Cotton Care instructions Machine Wash Origin Imported Neck styleCrew Neck About this item THE FIT - Standard-fit men's T-shirt for a classic look. THE FEEL - Crafted from a soft, 5.5 oz. cotton or cotton blend. THE LOOK - Classic short-sleeve style with ribbed crew neckline and soft back neck tape. SPOT THE C - Iconic C logo at the chest and left sleeve are recognizable on and off the field. Note: C logo patch color may vary from image.", 10, NOW(), NOW()),
  ('Men\'s Shirt Blue', 'Champion', 700, 700, 0.85, 'https://m.media-amazon.com/images/I/71Xgx41+NyL._AC_SX569_.jpg', "Product details Fabric type 100% Cotton Care instructions Machine Wash Origin Imported Neck styleCrew Neck About this item THE FIT - Standard-fit men's T-shirt for a classic look. THE FEEL - Crafted from a soft, 5.5 oz. cotton or cotton blend. THE LOOK - Classic short-sleeve style with ribbed crew neckline and soft back neck tape. SPOT THE C - Iconic C logo at the chest and left sleeve are recognizable on and off the field. Note: C logo patch color may vary from image.", 10, NOW(), NOW()),
  ('Men\'s Polo Shirt Black', 'Cossniss', 800, 600, 1, 'https://m.media-amazon.com/images/I/7176fMiEuWL._AC_SX522_.jpg', "Product details Fabric type 100% Cotton Care instructions Machine Wash Origin Imported Neck styleCrew Neck About this item THE FIT - Standard-fit men's T-shirt for a classic look. THE FEEL - Crafted from a soft, 5.5 oz. cotton or cotton blend. THE LOOK - Classic short-sleeve style with ribbed crew neckline and soft back neck tape. SPOT THE C - Iconic C logo at the chest and left sleeve are recognizable on and off the field. Note: C logo patch color may vary from image.", 10, NOW(), NOW()),
  ('Men\'s Polo Shirt White', 'Cossniss', 800, 600, 0.95, 'https://m.media-amazon.com/images/I/81SIQOx9syL._AC_SX522_.jpg', "Product details Fabric type 100% Cotton Care instructionsMachine Wash OriginImported Neck styleCrew Neck About this item THE FIT - Standard-fit men's T-shirt for a classic look. THE FEEL - Crafted from a soft, 5.5 oz. cotton or cotton blend. THE LOOK - Classic short-sleeve style with ribbed crew neckline and soft back neck tape. SPOT THE C - Iconic C logo at the chest and left sleeve are recognizable on and off the field. Note: C logo patch color may vary from image.", 10, NOW(), NOW()),
  ('Men\'s Polo Shirt Blue', 'Cossniss', 800, 600, 0.8, 'https://m.media-amazon.com/images/I/817BxHCJhwL._AC_SX522_.jpg', "Product details Fabric type 100% Cotton Care instructions Machine Wash Origin Imported Neck styleCrew Neck About this item THE FIT - Standard-fit men's T-shirt for a classic look. THE FEEL - Crafted from a soft, 5.5 oz. cotton or cotton blend. THE LOOK - Classic short-sleeve style with ribbed crew neckline and soft back neck tape. SPOT THE C - Iconic C logo at the chest and left sleeve are recognizable on and off the field. Note: C logo patch color may vary from image.", 10, NOW(), NOW()),
  ('Men\'s Short Classic-Fit Black', 'Amazon', 450, 450, 0.88, 'https://m.media-amazon.com/images/I/71wcnt4mVuL._AC_SX569_.jpg', "Product details Fabric type 100% Cotton Care instructionsMachine Wash Warm, Tumble Dry nOriginImported Closure typeZipper About this item CLASSIC FIT: Roomy through hip and thigh with straight leg. Sits at the waist. COTTON TWILL: Gently structured cotton twill that is naturally breathable with a garment wash for a soft, durable hand. EVERYDAY SHORTS: Classic khaki chino shorts in a non-stretch, garment-washed fabric for a versatile warm-weather wardrobe staple. DETAILS: Zip fly with button at waist, front slant pockets, and button-through back welt pockets. INSEAM: 9 on US size 32.", 10, NOW(), NOW()),
  ('Men\'s Short Classic-Fit White', 'Amazon', 450, 450, 0.95, 'https://m.media-amazon.com/images/I/71OuGHBsLKL._AC_SY550_.jpg', "Product details Fabric type 100% Cotton Care instructionsMachine Wash Warm, Tumble Dry nOriginImported Closure typeZipper About this item CLASSIC FIT: Roomy through hip and thigh with straight leg. Sits at the waist. COTTON TWILL: Gently structured cotton twill that is naturally breathable with a garment wash for a soft, durable hand. EVERYDAY SHORTS: Classic khaki chino shorts in a non-stretch, garment-washed fabric for a versatile warm-weather wardrobe staple. DETAILS: Zip fly with button at waist, front slant pockets, and button-through back welt pockets. INSEAM: 9 on US size 32.", 10, NOW(), NOW()),
  ('Men\'s Short Classic-Fit Blue', 'Amazon', 450, 450, 0.8, 'https://m.media-amazon.com/images/I/71oa8K-iZKL._AC_SY550_.jpg', "Product details Fabric type 100% Cotton Care instructionsMachine Wash Warm, Tumble Dry nOriginImported Closure typeZipper About this item CLASSIC FIT: Roomy through hip and thigh with straight leg. Sits at the waist. COTTON TWILL: Gently structured cotton twill that is naturally breathable with a garment wash for a soft, durable hand. EVERYDAY SHORTS: Classic khaki chino shorts in a non-stretch, garment-washed fabric for a versatile warm-weather wardrobe staple. DETAILS: Zip fly with button at waist, front slant pockets, and button-through back welt pockets. INSEAM: 9 on US size 32.", 10, NOW(), NOW()),
  ('Men\'s Slim-Fit Pants Black', 'Amazon', 900, 900, 0.95, 'https://m.media-amazon.com/images/I/71Avxf+kbHL._AC_SX569_.jpg', "Product details Fabric type 100% Cotton Care instructionsMachine Wash Warm, Tumble Dry nOriginImported Closure typeZipper About this item CLASSIC FIT: Roomy through hip and thigh with straight leg. Sits at the waist. COTTON TWILL: Gently structured cotton twill that is naturally breathable with a garment wash for a soft, durable hand. EVERYDAY SHORTS: Classic khaki chino shorts in a non-stretch, garment-washed fabric for a versatile warm-weather wardrobe staple. DETAILS: Zip fly with button at waist, front slant pockets, and button-through back welt pockets. INSEAM: 9 on US size 32.", 10, NOW(), NOW()),
  ('Men\'s Slim-Fit Pants White', 'Amazon', 900, 900, 0.97, 'https://m.media-amazon.com/images/I/61kwAigA6VL._AC_SY550_.jpg', "Product details Fabric type 100% Cotton Care instructionsMachine Wash Warm, Tumble Dry nOriginImported Closure typeZipper About this item CLASSIC FIT: Roomy through hip and thigh with straight leg. Sits at the waist. COTTON TWILL: Gently structured cotton twill that is naturally breathable with a garment wash for a soft, durable hand. EVERYDAY SHORTS: Classic khaki chino shorts in a non-stretch, garment-washed fabric for a versatile warm-weather wardrobe staple. DETAILS: Zip fly with button at waist, front slant pockets, and button-through back welt pockets. INSEAM: 9 on US size 32.", 10, NOW(), NOW()),
  ('Men\'s Slim-Fit Pants Blue', 'Amazon', 900, 900, 0.81, 'https://m.media-amazon.com/images/I/71Fo0AlxOyL._AC_SY550_.jpg', "Product details Fabric type 100% Cotton Care instructionsMachine Wash Warm, Tumble Dry nOriginImported Closure typeZipper About this item CLASSIC FIT: Roomy through hip and thigh with straight leg. Sits at the waist. COTTON TWILL: Gently structured cotton twill that is naturally breathable with a garment wash for a soft, durable hand. EVERYDAY SHORTS: Classic khaki chino shorts in a non-stretch, garment-washed fabric for a versatile warm-weather wardrobe staple. DETAILS: Zip fly with button at waist, front slant pockets, and button-through back welt pockets. INSEAM: 9 on US size 32.", 10, NOW(), NOW()),
  ('Women\'s Tshirt Black', 'Automet', 700, 300, 0.84, 'https://m.media-amazon.com/images/I/71NgezgFidL._AC_SY550_.jpg', "Product details Fabric type60%Polyester,35%Rayon,5%Sapndex Care instructionsMachine Wash Origin Imported Closure type Pull On About this item Material:The short sleeve tops is made of 35%rayon+60%polyester+5 %spandex，solid color, super soft, lightweight, breathable and stretchy Design:basic t-shirts,U neck,short sleeve,solid color,loose fit,lightweight,comfy under shirts,casual style, Match: This womens short sleeve T shirts is perfect match with lounge shorts/sweatpants/jeans/pants in summer/spring/fall,Also can wear as a undershirt and match with casual coat or jacket. Creat a chic and stylish daily look. Occasion: Casual lounge t shirts, perfect for daily life/workout/travel/running/home/office/vacation/sport/gym/yoga/going out. Note: Machine wash with a laundry bag, hand wash cold, do not bleach.", 10, NOW(), NOW()),
  ('Women\'s Tshirt White', 'Automet', 700, 300, 1, 'https://m.media-amazon.com/images/I/71M8CON5miL._AC_SY550_.jpg', "Product details Fabric type60%Polyester,35%Rayon,5%Sapndex Care instructionsMachine Wash Origin Imported Closure type Pull On About this item Material:The short sleeve tops is made of 35%rayon+60%polyester+5 %spandex，solid color, super soft, lightweight, breathable and stretchy Design:basic t-shirts,U neck,short sleeve,solid color,loose fit,lightweight,comfy under shirts,casual style, Match: This womens short sleeve T shirts is perfect match with lounge shorts/sweatpants/jeans/pants in summer/spring/fall,Also can wear as a undershirt and match with casual coat or jacket. Creat a chic and stylish daily look. Occasion: Casual lounge t shirts, perfect for daily life/workout/travel/running/home/office/vacation/sport/gym/yoga/going out. Note: Machine wash with a laundry bag, hand wash cold, do not bleach.", 10, NOW(), NOW()),
  ('Women\'s Tshirt Blue', 'Automet', 700, 300, 0.7, 'https://m.media-amazon.com/images/I/71NlXBhxifL._AC_SY550_.jpg', "Product details Fabric type60%Polyester,35%Rayon,5%Sapndex Care instructionsMachine Wash Origin Imported Closure type Pull On About this item Material:The short sleeve tops is made of 35%rayon+60%polyester+5 %spandex，solid color, super soft, lightweight, breathable and stretchy Design:basic t-shirts,U neck,short sleeve,solid color,loose fit,lightweight,comfy under shirts,casual style, Match: This womens short sleeve T shirts is perfect match with lounge shorts/sweatpants/jeans/pants in summer/spring/fall,Also can wear as a undershirt and match with casual coat or jacket. Creat a chic and stylish daily look. Occasion: Casual lounge t shirts, perfect for daily life/workout/travel/running/home/office/vacation/sport/gym/yoga/going out. Note: Machine wash with a laundry bag, hand wash cold, do not bleach.", 10, NOW(), NOW()),
  ('Women\'s Summer Top Black', 'Wiholl', 400, 300, 0.84, 'https://m.media-amazon.com/images/I/71pIB9vI1JL._AC_SY550_.jpg', "Product details Fabric type60%Polyester,35%Rayon,5%Sapndex Care instructionsMachine Wash Origin Imported Closure type Pull On About this item Material:The short sleeve tops is made of 35%rayon+60%polyester+5 %spandex，solid color, super soft, lightweight, breathable and stretchy Design:basic t-shirts,U neck,short sleeve,solid color,loose fit,lightweight,comfy under shirts,casual style, Match: This womens short sleeve T shirts is perfect match with lounge shorts/sweatpants/jeans/pants in summer/spring/fall,Also can wear as a undershirt and match with casual coat or jacket. Creat a chic and stylish daily look. Occasion: Casual lounge t shirts, perfect for daily life/workout/travel/running/home/office/vacation/sport/gym/yoga/going out. Note: Machine wash with a laundry bag, hand wash cold, do not bleach.", 10, NOW(), NOW()),
  ('Women\'s Summer Top White', 'Wiholl', 400, 300, 0.9, 'https://m.media-amazon.com/images/I/61xXyhxqdkL._AC_SY550_.jpg', "Product details Fabric type60%Polyester,35%Rayon,5%Sapndex Care instructionsMachine Wash Origin Imported Closure type Pull On About this item Material:The short sleeve tops is made of 35%rayon+60%polyester+5 %spandex，solid color, super soft, lightweight, breathable and stretchy Design:basic t-shirts,U neck,short sleeve,solid color,loose fit,lightweight,comfy under shirts,casual style, Match: This womens short sleeve T shirts is perfect match with lounge shorts/sweatpants/jeans/pants in summer/spring/fall,Also can wear as a undershirt and match with casual coat or jacket. Creat a chic and stylish daily look. Occasion: Casual lounge t shirts, perfect for daily life/workout/travel/running/home/office/vacation/sport/gym/yoga/going out. Note: Machine wash with a laundry bag, hand wash cold, do not bleach.", 10, NOW(), NOW()),
  ('Women\'s Summer Top Blue', 'Wiholl', 400, 300, 0.8, 'https://m.media-amazon.com/images/I/71yTSdlPuvL._AC_SY550_.jpg', "Product details Fabric type60%Polyester,35%Rayon,5%Sapndex Care instructionsMachine Wash Origin Imported Closure type Pull On About this item Material:The short sleeve tops is made of 35%rayon+60%polyester+5 %spandex，solid color, super soft, lightweight, breathable and stretchy Design:basic t-shirts,U neck,short sleeve,solid color,loose fit,lightweight,comfy under shirts,casual style, Match: This womens short sleeve T shirts is perfect match with lounge shorts/sweatpants/jeans/pants in summer/spring/fall,Also can wear as a undershirt and match with casual coat or jacket. Creat a chic and stylish daily look. Occasion: Casual lounge t shirts, perfect for daily life/workout/travel/running/home/office/vacation/sport/gym/yoga/going out. Note: Machine wash with a laundry bag, hand wash cold, do not bleach.", 10, NOW(), NOW()),
  ('Women\'s Fleece Short Black', 'Amazon', 900, 900, 0.75, 'https://m.media-amazon.com/images/I/61yJuhyPNOL._AC_SY550_.jpg', "Fabric type60% Cotton, 40% Polyester Care instructionsMachine Wash Warm, Tumble Dry OriginImported Closure typeElastic About this item REGULAR FIT: Close but comfortable fit through hip and thigh with ease through the leg opening. Mid rise, sits below the natural waist. COZY BRUSHED BACK FLEECE: Buttery soft and comfy midweight cotton blend fleece with brushed interior. EVERYWHERE SWEATSHORT: These everyday fleece shorts give you ultimate comfort and versatility whether you are at the gym, running errands, going for a walk, or just lounging at home. DETAILS: Features a drawstring pull-on waistband for all-day comfort and the perfect fit, and front slant pocket to hold the essentials. INSEAM: 3 1/2“ on US size S.", 10, NOW(), NOW()),
  ('Women\'s Fleece Short White', 'Amazon', 900, 900, 0.9, 'https://m.media-amazon.com/images/I/71Q6usnIF8L._AC_SY550_.jpg', "Fabric type60% Cotton, 40% Polyester Care instructionsMachine Wash Warm, Tumble Dry OriginImported Closure typeElastic About this item REGULAR FIT: Close but comfortable fit through hip and thigh with ease through the leg opening. Mid rise, sits below the natural waist. COZY BRUSHED BACK FLEECE: Buttery soft and comfy midweight cotton blend fleece with brushed interior. EVERYWHERE SWEATSHORT: These everyday fleece shorts give you ultimate comfort and versatility whether you are at the gym, running errands, going for a walk, or just lounging at home. DETAILS: Features a drawstring pull-on waistband for all-day comfort and the perfect fit, and front slant pocket to hold the essentials. INSEAM: 3 1/2“ on US size S.", 10, NOW(), NOW()),
  ('Women\'s Biker Short Black', 'Fullsoft', 300, 300, 0.8, 'https://m.media-amazon.com/images/I/71V1N1CkO+L._AC_SX466_.jpg', "Fabric type60% Cotton, 40% Polyester Care instructionsMachine Wash Warm, Tumble Dry OriginImported Closure typeElastic About this item REGULAR FIT: Close but comfortable fit through hip and thigh with ease through the leg opening. Mid rise, sits below the natural waist. COZY BRUSHED BACK FLEECE: Buttery soft and comfy midweight cotton blend fleece with brushed interior. EVERYWHERE SWEATSHORT: These everyday fleece shorts give you ultimate comfort and versatility whether you are at the gym, running errands, going for a walk, or just lounging at home. DETAILS: Features a drawstring pull-on waistband for all-day comfort and the perfect fit, and front slant pocket to hold the essentials. INSEAM: 3 1/2“ on US size S.", 10, NOW(), NOW()),
  ('Women\'s Biker Short White', 'Fullsoft', 300, 300, 0.85, 'https://m.media-amazon.com/images/I/61rW0SQE3kL._AC_SX466_.jpg', "Fabric type60% Cotton, 40% Polyester Care instructionsMachine Wash Warm, Tumble Dry OriginImported Closure typeElastic About this item REGULAR FIT: Close but comfortable fit through hip and thigh with ease through the leg opening. Mid rise, sits below the natural waist. COZY BRUSHED BACK FLEECE: Buttery soft and comfy midweight cotton blend fleece with brushed interior. EVERYWHERE SWEATSHORT: These everyday fleece shorts give you ultimate comfort and versatility whether you are at the gym, running errands, going for a walk, or just lounging at home. DETAILS: Features a drawstring pull-on waistband for all-day comfort and the perfect fit, and front slant pocket to hold the essentials. INSEAM: 3 1/2“ on US size S.", 10, NOW(), NOW()),
  ('Women\'s Biker Short Blue', 'Fullsoft', 300, 300, 1, 'https://m.media-amazon.com/images/I/71d2J4JJspL._AC_SX466_.jpg', "Fabric type60% Cotton, 40% Polyester Care instructionsMachine Wash Warm, Tumble Dry OriginImported Closure typeElastic About this item REGULAR FIT: Close but comfortable fit through hip and thigh with ease through the leg opening. Mid rise, sits below the natural waist. COZY BRUSHED BACK FLEECE: Buttery soft and comfy midweight cotton blend fleece with brushed interior. EVERYWHERE SWEATSHORT: These everyday fleece shorts give you ultimate comfort and versatility whether you are at the gym, running errands, going for a walk, or just lounging at home. DETAILS: Features a drawstring pull-on waistband for all-day comfort and the perfect fit, and front slant pocket to hold the essentials. INSEAM: 3 1/2“ on US size S.", 10, NOW(), NOW());


-- GENERATE CATEGORIES
INSERT INTO categories(name, created_at, updated_at) VALUES
  ('men', NOW(), NOW()),
  ('women', NOW(), NOW()),
  ('shirt', NOW(), NOW()),
  ('short', NOW(), NOW()),
  ('pants', NOW(), NOW()),
  ('black', NOW(), NOW()),
  ('white', NOW(), NOW()),
  ('blue', NOW(), NOW())
  ;


-- -- ATTACH CATEGORIES TO PRODUCTS
-- -- Product 1
-- INSERT INTO product_categories(categories_id, products_id, created_at, updated_at) VALUES
--   (1, 1, NOW(), NOW()), -- gray
--   (2, 1, NOW(), NOW()), -- black
--   (3, 1, NOW(), NOW()); -- chair
