-- MySQL Script generated by MySQL Workbench
-- Sat Aug 26 04:05:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema foriou
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `foriou` DEFAULT CHARACTER SET utf8 ;
USE `foriou` ;

-- -----------------------------------------------------
-- Table `foriou`.`admins`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `foriou`.`categories` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `foriou`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foriou`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_admin` INT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL,
  `contact` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `salt` VARCHAR(100) NULL DEFAULT NULL,
  `zip_code` INT NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(95) NULL DEFAULT NULL,
  `birthdate` DATETIME NULL,
  `city_name` VARCHAR(60) NULL DEFAULT NULL,
  `state_name` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `foriou`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foriou`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_shipping_id` INT NOT NULL,
  `customer_billing_id` INT NOT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_customers1_idx` (`customer_shipping_id` ASC) VISIBLE,
  INDEX `fk_orders_customers2_idx` (`customer_billing_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customers1`
    FOREIGN KEY (`customer_shipping_id`)
    REFERENCES `foriou`.`customers` (`id`),
  CONSTRAINT `fk_orders_customers2`
    FOREIGN KEY (`customer_billing_id`)
    REFERENCES `foriou`.`customers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `foriou`.`product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foriou`.`product_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `foriou`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foriou`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `name` VARCHAR(50) NULL DEFAULT NULL,
  `vendor` VARCHAR(50) NULL DEFAULT NULL,
  `unit_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `discounted_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `rating` DECIMAL(3,1) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `inventory_count` INT NULL DEFAULT NULL,
  `quantity_sold` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_categories1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `foriou`.`product_categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `foriou`.`product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foriou`.`product_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `categories_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_categories_categories1_idx` (`categories_id` ASC) VISIBLE,
  INDEX `fk_product_categories_products1_idx` (`products_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_categories_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_categories_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `foriou`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;

-- -----------------------------------------------------
-- Table `foriou`.`order_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `foriou`.`order_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `unit_price` DECIMAL(10,2) NULL DEFAULT NULL,
  `product_name` VARCHAR(50) NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_lists_products1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_order_details_orders1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_details_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `foriou`.`orders` (`id`),
  CONSTRAINT `fk_product_lists_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `foriou`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
